### PR TITLE
refactor trainmap

### PR DESCRIPTION
**Pull request by petabyteboy**
Online at https://amalthea.pbb.lc/map (sometimes, when my laptop is on and the dev environment is running).

### CODE REVIEW

**Comment by petabyteboy** [comment]
If you are at 36C3 and interested in talking about this, call me at DECT 4567.

**Comment by marudor** [comment]
I tried it.
I dislike how the positions are marked now. The circles are quite big.
(Not that it currently looks that great, I would just like to prevent it to be even worse)

**Comment by petabyteboy** [comment]
Thanks for taking a look. I had showed the new design to multiple people and some found it better while others found it worse than the old design. I personally prefer this design, but I will try to improve it.

**Comment by marudor** [comment]
Closing as nothing happened here.
If you come back to this feel free to create a new PR.

**Pull request closed without merging**
